name: Validate
on: [ push ]

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.12' ] # use minimum supported version
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Run lint
        run: make lint
